
services:
  mssql:
    hostname: mssql_todo
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    volumes:
      - ./data/:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD_FILE=/run/secrets/mssql_todo_password
    secrets:
      - mssql_todo_password
  
secrets:
  mssql_todo_password:
    file: ./mssql_todo_password
